on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: codeacademy2020registerniilo.azurecr.io
          username: ${{ steps.create-acr.outputs.acr_username }}
          password: ${{ steps.create-acr.outputs.acr_password }}

      - name: Build and push image to ACR
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/userservice" -f  "userservice/Dockerfile" -t codeacademy2020registerniilo.azurecr.io/codeacademy2020userservice:${{ github.sha }}
          docker build "$GITHUB_WORKSPACE/fashionservice" -f  "fashionservice/Dockerfile" -t codeacademy2020registerniilo.azurecr.io/codeacademy2020fashionservice:${{ github.sha }}
          docker push codeacademy2020registerniilo.azurecr.io/codeacademy2020userservice:${{ github.sha }}
          docker push codeacademy2020registerniilo.azurecr.io/codeacademy2020fashionservice:${{ github.sha }}

      - uses: azure/k8s-set-context@v1
        id: login
        with:
          kubeconfig: ${{ secrets.aks_codeacademy2020cluster_kubeConfig }}

      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep codeacademy2020cluster96a5 | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace codeacademy2020cluster96a5`
          fi

      - uses: azure/k8s-create-secret@v1
        with:
          namespace: codeacademy2020cluster96a5
          container-registry-url: codeacademy2020registerniilo.azurecr.io
          container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
          container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
          secret-name: codeacademy2dockerauth

      - uses: azure/k8s-deploy@v1
        with:
          namespace: codeacademy2020cluster96a5
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            codeacademy2020registerniilo.azurecr.io/codeacademy2020userservice:${{ github.sha }}
            codeacademy2020registerniilo.azurecr.io/codeacademy2020fashionservice:${{ github.sha }}
          imagepullsecrets: |
            codeacademy2dockerauth
